### PR TITLE
NaN is equal to NaN

### LINKED ISSUE #83: NaN as a special case
It would be nice if NaN was treaded as a special case, so the following would be OK:

``` javascript
t.deepEqual({ prop: NaN }, { prop: NaN });
```

Right now the diff says:

```
diff:    |
  {
    "prop" : NaN, // != NaN
  }
```

and that is just a bit odd.

### PR DESCRIPTION
**Pull request by AndreasMadsen**
Fixes #83

This changes:
- t.deepEqual
- t.equal
- t.like

and there opposites

### CODE REVIEW

**Comment by othiym23** [comment]
This is an oddity of IEEE754, but that doesn't mean that `tap` should paper over it unless a developer specifically wants that behavior. IMHO this shouldn't be the default.

**Comment by isaacs** [comment]
I'd be ok with adding `t.is()` and `t.deepIs()` methods, but changing `equal` is not a good idea.

**Comment by isaacs** [comment]
Actually, `like()` is probably fine to change in this way.

**Comment by pc-dedelhart** [comment]
Can't you do an isNaN() around the result and compare the two?

**Pull request closed without merging**
