### PR TITLE
fix: json5 security vulnerability

### LINKED ISSUE #852: json5 vulnerability in 16.3.2
Hi everyone! 

There is a vulnerability in the bundled dependencies of 16.3.2 with json5. I have tried overriding this locally but am not having any success. Json5 needs to be updated to >=2.2.2. Is there a way to fix this without a new release in @isaacs/import-jsx as well as here?

For context of what I did: 
`"devDependencies": {
        "json5": "^2.2.2"
    },"overrides": {
        "tap@16.3.2": {
            "@isaacs/import-jsx@4.0.1": {
                "@babel/core@7.17.8": {
                    "json5": "$json5"
                }
            }
        }
    }`

Thank you!

### PR DESCRIPTION
**Pull request by theoludwig**
Fixes #852 

Hello! :wave:

[json5](https://github.com/json5/json5) has been impacted by a security vulnerability: [Prototype Pollution in JSON5 via Parse Method (GHSA-9c47-m6qq-7p4h)](https://github.com/json5/json5/security/advisories/GHSA-9c47-m6qq-7p4h).

Even if `json5` is not a dependency of `tap`, it uses dependencies that use it, hence when installing `tap`, we got this output from `npm install`: 

```txt
added 201 packages, and audited 364 packages in 9s

30 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

When running `npm audit fix`:
```txt
npm WARN audit fix json5@2.2.1 node_modules/tap/node_modules/json5
npm WARN audit fix json5@2.2.1 is a bundled dependency of
npm WARN audit fix json5@2.2.1 tap@16.3.2 at node_modules/tap
npm WARN audit fix json5@2.2.1 It cannot be fixed automatically.
npm WARN audit fix json5@2.2.1 Check for updates to the tap package.

up to date, audited 364 packages in 846ms

30 packages are looking for funding
  run `npm fund` for details

# npm audit report

json5  <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/tap/node_modules/json5

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

Here's what I did:
```sh
rm -rf node_modules
rm -rf package-lock.json
npm install
```
This fixes the issue, only `package-lock.json` has been updated.

### CODE REVIEW

**Comment by nicolasolmospurple** [comment]
😃 I've tested this fix in my computer and it removes the vulnerability error. I'd love to see it merged!

Tested on: `Node.js v16.13.0`

**Comment by ksparakis** [comment]
Works for me as well @isaacs would love to have this merged in.

**Comment by theoludwig** [comment]
This has been fixed in: https://github.com/tapjs/node-tap/commit/5c5e3e370a5237be7841e303fc5f88a581d12a0d
Also released as v16.3.3. :+1:

**Comment by larsknutson** [comment]
Thanks!

**Pull request closed without merging**
