### PR TITLE
add(typescript): typing defination file with unit tests (#237)

### PR DESCRIPTION
**Pull request by huan**
This PR made from all the TypeScript resources from the Issues & Pull Requests before. Include: #237 #238 #256 #381 .

What this PR do is:
1. Added `index.d.ts` to the root directory, added `types` entry to `package.json`;
1. Added `test/typescript.ts` unit test to make sure the basic TypeScript system works right;
1. Added TypeScript linting tool to do **Static Type Checking**;
1. Integrate the TypeScript test & lint scripts to `package.json`, which can be run automatically by executing `npm test`;

I really want to use `import { test } from 'tap'` with the Type Checking / IDE IntelliSense, instead of `const { test } = require('tap')` and have to check the document from time to time.

@isaacs Please let me know if there need do any future works on it, Thanks!

### CODE REVIEW

**Comment by huan** [comment]
TravisCI passed! :smiley:

**Comment by ORESoftware** [comment]
nice work, I will be happy to use this thanks!

**Comment by huan** [comment]
ping @isaacs

**Comment by huan** [comment]
AppVeyor is failing because of they have a node runtime called `node.EXE` but we are checking for `node.exe`.

<https://ci.appveyor.com/project/isaacs/node-tap/build/446/job/46d8untfsgpj54yv#L5078>
```shell
              found: '    not ok 1 - node.EXE ./test/test/nesting.js # time=650.715ms'
              pattern: >-
                /^    not ok 1 \- .*(node|iojs)(.exe)? \.\/test\/test\/nesting\.js #
                time=[0-9.]+(ms)?$/
```

Will try to fix it.

**Comment by huan** [comment]
Windows CI is passed after we ignore the case for `node.EXE` 

I believe this is the reason why the Appveyor CI looks not stable in the commit history. ;-]

**Comment by huan** [comment]
ping @isaacs

**Comment by huan** [comment]
Hi @isaacs, this PR have included all requirements that we discussed before, especially the unit tests.

I'd like to contribute more if we need additional works on it. If so, please feel free to let me know what you want me to do before this PR could be able to be merged.

I use tap in lots of my TypeScript projects, it's a pain for me that can not see any IDE IntelliSense and without any static typing check. 

Looking forward to hearing back from you, thanks!

**Comment by kazimuth** [comment]
Ping, is there anything else that needs to be done for this to be merged?

**Comment by isaacs** [comment]
Hi, sorry for the delay, thank you for your patience while v11 was being completed.

I've ported everything up to latest and squashed in my `ts` branch here: https://github.com/tapjs/node-tap/commit/ts

The only issue I still have with this is how am I to know that it's accurate and complete?  Even though many new methods are added on v11, it seems to be fine with them not being covered in the typescript definition.  Is there a way to make it fail on un-type-defined methods?

**Comment by isaacs** [comment]
Ack, worse yet, the `Test.prototype.current()` method is removed, and the type definition checks are fine with it still being in the type definition.  That's exactly what I was afraid of.  I will break this thing, and not notice.  That's not ok.

Without automated testing, including automatic test coverage enforcement, I can't take responsibility for this.  I'm sorry.

I'm happy to merge this into master if that concern can be addressed somehow.

**Comment by huan** [comment]
Hi @isaacs,

Glad to see you just released v11, and I understand that you are still worrying the mismatch between the Typing Definition and the JS code.

As my 2 cents, it will always be acceptable for me to have a buggy typing definition file instead of none. ;-p

However, if we want to be the perfect match, the ultimate solution would write the interface JS code to TS, and we use `tsc` to compile TS to JS and then we will have an absolutely matched type definition file.

For example, I just had a quick look at tap source code, it seems the API is inside the following two files:
1. https://github.com/tapjs/node-tap/blob/master/lib/test.js
1. https://github.com/tapjs/node-tap/blob/master/lib/tap.js

They are all written in ES6 class, which means it could be very easy to rewrite in TypeScript. If so, then we will be never worried about the mismatch anymore.

However, I do not know if this solution is acceptable for @isaacs. If you think it is acceptable, I'd like to send you a PR to demo this.

**Comment by isaacs** [comment]
Yeah, I'm really not interested in migrating to typescript for this module right now.  Maybe the best approach is to take this over to https://github.com/definitelytyped or something.

**Comment by isaacs** [comment]
According to @iffy in [this comment](https://github.com/tapjs/node-tap/pull/381#issuecomment-348976674), the branch used in #381 may meet the necessary criteria?  If anyone wants to take a look, I'm still open to landing this, provided there's checks against me breaking it later :)

**Comment by ericmorand** [comment]
Any news on this?

**Pull request closed without merging**
