### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by jsumners**
Travis no longer works. I believe I have replicated the Travis configuration with this PR.

### CODE REVIEW

**Comment by jsumners** [comment]
The Travis configuration only ran the tests on Linux. I have added in running the tests on Windows and macOS. The result is a failure on Windows -- https://github.com/jsumners/node-tap/runs/1900077163?check_suite_focus=true#step:5:14913

Should I disable Windows testing? Or does anyone know what needs to be done to make the tests work there? I do not have a Windows system for development.

**Comment by coreyfarrell** [comment]
Maybe we just migrate node-tap master from travis without changing the testing matrix, then try to enable windows testing for [v15](https://github.com/tapjs/node-tap/tree/v15) (the next version)?  tap v15 has significant code and tests moved to https://github.com/tapjs/libtap.  The libtap repository has windows testing enabled so maybe we'll run into less issues adding Windows CI to v15.

**Comment by jsumners** [comment]
> Maybe we just migrate node-tap master from travis without changing the testing matrix, then try to enable windows testing for [v15](https://github.com/tapjs/node-tap/tree/v15?rgh-link-date=2021-02-15T13%3A18%3A35Z) (the next version)? tap v15 has significant code and tests moved to [tapjs/libtap](https://github.com/tapjs/libtap). The libtap repository has windows testing enabled so maybe we'll run into less issues adding Windows CI to v15.

👍

**Comment by jsumners** [comment]
@coreyfarrell PR updated

**Comment by jsumners** [comment]
Run report -- https://github.com/jsumners/node-tap/actions/runs/569796958

**Pull request closed without merging**
