### PR TITLE
fixes deep equals

### PR DESCRIPTION
**Pull request by ghost**
`t.deepEqual()` and company return false negatives when the key order doesn't match for two non-Array objects.

### CODE REVIEW

**Comment by jhs** [comment]
Love it! I'm a big deepEqual user myself. IMHO I prefer not to put failing tests in their own commits because `git bisect` might checkout that commit and your test suite will fail, complicating the job of fixing the _real_ bug.

**Comment by ghost** [comment]
I like it better when failing tests have their own commits so I can more easily ditch an implementation change designed to pass the test without discarding the test.

**Comment by isaacs** [comment]
Commits can be squashed or split easily enough.  Imo, it's best for pull reqs to reflect the details as clearly as possible (usually in many commits), and then (usually) get squashed into a single commit in the upstream (or merged with `--no-ff` if it's worth keeping the detail.)

**Comment by isaacs** [comment]
merged and pushed to all the places.

**Pull request closed without merging**
