### PR TITLE
Add icepick to the Tap 100 club.

### PR DESCRIPTION
**Pull request by aearly**

### CODE REVIEW

**Comment by isaacs** [comment]
Landed and published, thanks!

**Comment by aearly** [comment]
Err, did you mean to close, rather than merge?

**Comment by isaacs** [comment]
Yeah, landed out of GH's green button, on eff2da88029a11984d3a39de753057dc0ff3c39c.

**Comment by isaacs** [comment]
er, 37651c6e769c2dcaa6ee622615564038f02e585e rather.

**Pull request closed without merging**
