### PR TITLE
fix Test.prototype.test optional arguments (issue #244)

### PR DESCRIPTION
**Pull request by maarten-t**
I'm not sure if the tests that I added use the preferred strategy of testing the fixed feature. I wasn't able to find examples of similar tests. Some test documentation or guidelines would be helpful. Part of the problem is that it wasn't immediately clear to me which parts of the code were the tests being tested and which were the tests of the tests.

Note that there is a suspicious line in `Test.prototype.test`, which I didn't touch out of cautiousness.
When the test name is missing, it's being set to its fallback value `'(unnamed test)'` at [line 453](https://github.com/themaarten/node-tap/blob/master/lib/test.js#L453) after it is used at [line 453](https://github.com/themaarten/node-tap/blob/master/lib/test.js#L448). Is it supposed to be in that order? It would make sense to set the fallback value around [line 433](https://github.com/themaarten/node-tap/blob/master/lib/test.js#L433).

### CODE REVIEW

**Comment by isaacs** [comment]
Setting the fallback earlier would be fine, but there's no harm in the current order.  All that'll happen is that it'll re-enter the function with `undefined` or some other falsey value, and then fall back the second time around.

For tests, in this case it'd be sufficient to modify one of the examples in `test/test/*.js` to set an options object and no name.  Then run `npm run regen-fixtures` to update the output fixtures.

**Comment by isaacs** [comment]
Test failures on Node 5 are unrelated.  The `function` value on throws changed from `Timer._onTimeout` to `null._onTimeout`, so I just need to update the test to allow for this.

**Comment by isaacs** [comment]
Landed on master, but slightly different implementation, and factored it out so that this bit could be unit tested explicitly.

Thanks!

**Comment by maarten-t** [comment]
Thank you!

**Pull request closed without merging**
